# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('salads', 'Cалаты'), ('first_meal', 'Первые блюда'), ('second_courses', 'Вторые блюда'), ('garnishes', 'Гарниры'), ('dessert', 'Десерты'), ('beverages', 'Напитки')], max_length=50, verbose_name='Категория')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_creation', models.DateField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('sum', models.IntegerField(verbose_name='Cумма заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('telegram_user_id', models.IntegerField(unique=True, verbose_name='Telegram User ID')),
            ],
            options={
                'verbose_name': 'Работника компании',
                'verbose_name_plural': 'Работники компании',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mo_cafe.Workers', to_field='telegram_user_id', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='orders',
            name='dishes',
            field=models.ManyToManyField(to='mo_cafe.Food', verbose_name='Блюда в заказе'),
        ),
    ]
