# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date_of_creation',
            field=models.DateField(verbose_name='Дата создания заказа'),
        ),
    ]
