# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='Food',
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
    ]
