# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-03 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_auto_20171104_0014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'Пункт меню', 'verbose_name_plural': 'Пунктов меню'},
        ),
    ]
