# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_auto_20171107_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultsMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_per_month', models.IntegerField(verbose_name='Стоимость заказов за месяц')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_app.Workers', to_field='telegram_user_id', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Итог месяца',
                'verbose_name_plural': 'Итоги месяца',
            },
        ),
    ]
