# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-04 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_auto_20171104_0016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'Пункт меню', 'verbose_name_plural': 'Пункты меню'},
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('salads', 'Cалаты'), ('first_meal', 'Первые блюда'), ('second_courses', 'Вторые блюда'), ('garnishes', 'Гарниры'), ('dessert', 'Десерты'), ('beverages', 'Напитки')], max_length=50, verbose_name='Категория'),
        ),
    ]
