# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-05 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_auto_20171105_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='order',
        ),
        migrations.AddField(
            model_name='orders',
            name='order',
            field=models.CharField(default='', max_length=1000, verbose_name='Заказ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='sum',
            field=models.IntegerField(default=0, verbose_name='Cумма заказа'),
            preserve_default=False,
        ),
    ]
