# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0006_auto_20171106_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='oreder1',
            field=models.ManyToManyField(to='django_app.Food'),
        ),
    ]
