# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0007_orders_oreder1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='oreder1',
            new_name='dishes',
        ),
    ]
