# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0008_auto_20171106_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order',
        ),
        migrations.AlterField(
            model_name='orders',
            name='dishes',
            field=models.ManyToManyField(to='django_app.Food', verbose_name='Блюда в заказе'),
        ),
    ]
